import { ArrowUpRight, Crosshair, Database, Download, MapPin, Maximize2, Minus, Plus, Radar, Satellite, Target, Zap } from 'lucide-react'
import { Card, ClassificationBadge, RiskBadge, SectionHeader } from './ui'
import type { DashboardPayload } from '../types'

export function KPIGrid({ data }: { data: DashboardPayload }) { return <div className="kpi-grid">{data.kpis.map((item) => <Card className={`kpi-card tone-${item.tone}`} key={item.label}><div className="kpi-top"><span>{item.label}</span><span className="kpi-icon">{item.tone === 'red' ? <Target size={16} /> : item.tone === 'amber' ? <Zap size={16} /> : item.tone === 'green' ? <Database size={16} /> : <Satellite size={16} />}</span></div><strong>{item.value}</strong><div className="kpi-meta"><span>{item.detail}</span><em>{item.trend}</em></div></Card>)}</div> }

export function ActivityChart({ data }: { data: DashboardPayload }) { const max = Math.max(...data.timeline.values, 1); const points = data.timeline.values.map((value, index) => `${(index / Math.max(data.timeline.values.length - 1, 1)) * 100},${100 - (value / max) * 82 - 8}`).join(' '); return <Card className="chart-card activity-card"><SectionHeader eyebrow="Temporal pattern" title="Thermal activity timeline" action={<span className="data-chip"><span className="live-dot" />Verified output</span>} /><div className="chart-wrap"><div className="y-axis"><span>{max.toLocaleString()}</span><span>{Math.round(max * .75).toLocaleString()}</span><span>{Math.round(max * .5).toLocaleString()}</span><span>{Math.round(max * .25).toLocaleString()}</span><span>0</span></div><div className="line-chart"><div className="grid-lines">{[0, 1, 2, 3, 4].map((line) => <i key={line} />)}</div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Thermal detections trend"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#28a9c7" stopOpacity=".34" /><stop offset="1" stopColor="#28a9c7" stopOpacity="0" /></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#area)" /><polyline points={points} fill="none" stroke="#42c4d7" strokeWidth="1.4" vectorEffect="non-scaling-stroke" /></svg><div className="x-axis">{data.timeline.labels.map((label) => <span key={label}>{label}</span>)}</div></div></div></Card> }

export function ClassificationChart({ data }: { data: DashboardPayload }) { const total = data.rowCount; const gradient = data.classificationDistribution.map((item, index) => { const start = data.classificationDistribution.slice(0, index).reduce((sum, entry) => sum + entry.value, 0); return `${item.color} ${start / total * 100}% ${(start + item.value) / total * 100}%` }).join(', '); return <Card className="classification-card"><SectionHeader eyebrow="Model output" title="Classification distribution" action={<button className="icon-button" title="Download distribution"><Download size={16} /></button>} /><div className="donut-layout"><div className="donut" style={{ background: `conic-gradient(${gradient})` }}><div><strong>{total.toLocaleString()}</strong><span>records</span></div></div><div className="legend">{data.classificationDistribution.map((item) => <div className="legend-row" key={item.label}><span className="legend-key" style={{ background: item.color }} />{item.label}<strong>{item.value}</strong></div>)}</div></div></Card> }

export function RiskDistribution({ data }: { data: DashboardPayload }) { const max = Math.max(...data.riskDistribution.map((item) => item.value), 1); return <Card className="risk-card"><SectionHeader eyebrow="Priority index" title="Risk distribution" action={<span className="muted-label">{data.rowCount.toLocaleString()} records</span>} /><div className="risk-list">{data.riskDistribution.map((item) => <div className="risk-row" key={item.label}><div className="risk-row-label"><span>{item.label}</span><strong>{item.count}</strong></div><div className="risk-track"><i style={{ width: `${item.value / max * 100}%`, background: item.color }} /></div></div>)}</div></Card> }

export function ThermalMapPreview({ data }: { data: DashboardPayload }) { const points = data.mapPoints.slice(0, 30); const left = (longitude: number) => Math.max(5, Math.min(92, (longitude - 68) / 30 * 100)); const top = (latitude: number) => Math.max(7, Math.min(88, (35 - latitude) / 28 * 100)); return <Card className="map-card"><SectionHeader eyebrow="Geospatial context" title="Thermal activity map" action={<button className="text-button">Open live map <ArrowUpRight size={14} /></button>} /><div className="map-stage"><div className="map-grid" /><div className="india-shape"><span className="map-region region-north">NORTH</span><span className="map-region region-central">CENTRAL</span><span className="map-region region-south">SOUTH</span></div>{points.map((point) => <div className={`map-point ${point.classification.includes('Industrial') ? 'industrial' : 'thermal'}`} style={{ left: `${left(point.longitude)}%`, top: `${top(point.latitude)}%` }} key={point.id} title={`${point.id} · ${point.classification}`}><span /><label>{point.id}</label></div>)}<div className="map-controls"><button title="Zoom in"><Plus size={14} /></button><button title="Zoom out"><Minus size={14} /></button><button title="Center map"><Crosshair size={14} /></button></div><div className="map-toolbar"><span className="demo-pill">VERIFIED OUTPUT</span><span><i className="thermal-key" /> thermal</span><span><i className="industrial-key" /> industrial</span></div><div className="map-caption"><MapPin size={13} /> India analysis area <span>·</span> {points.length} plotted test records</div></div></Card> }

export function RecentEvents({ data }: { data: DashboardPayload }) { return <Card className="events-card"><SectionHeader eyebrow="Triage queue" title="Recent priority events" action={<button className="text-button">View all events <ArrowUpRight size={14} /></button>} /><div className="table-scroll"><table><thead><tr><th>Event ID</th><th>Classification</th><th>Risk</th><th>FRP</th><th>Persistence</th><th>Location</th><th>Status</th></tr></thead><tbody>{data.events.map((event) => <tr key={event.id}><td className="event-id">{event.id}</td><td><ClassificationBadge value={event.classification} /></td><td><RiskBadge level={event.risk} score={event.score} /></td><td>{event.frp} MW</td><td>{event.persistence}</td><td>{event.location}</td><td><span className={`status-text status-${event.status.toLowerCase().replace(' ', '-')}`}><i />{event.status}</span></td></tr>)}</tbody></table></div><div className="table-note"><Radar size={13} /> VERIFIED MODEL OUTPUT · Source: {data.source}</div></Card> }

export function OverviewDashboard({ data }: { data: DashboardPayload }) { return <div className="overview"><div className="snapshot-banner"><div><span className="eyebrow">Verified analysis snapshot</span><h2>India thermal intelligence, 2024</h2></div><div className="snapshot-meta"><span><Satellite size={15} /> NASA FIRMS / VIIRS</span><span><Database size={15} /> {data.rowCount.toLocaleString()} fused records</span><button className="outline-button"><Maximize2 size={14} /> Fullscreen</button></div></div><KPIGrid data={data} /><div className="dashboard-grid"><ActivityChart data={data} /><ClassificationChart data={data} /><ThermalMapPreview data={data} /><RiskDistribution data={data} /><RecentEvents data={data} /></div></div> }
