import { useEffect, useMemo, useState } from 'react'
import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom'
import { CircleAlert, ChevronDown, Download, FileText, Flame, Gauge, Layers, Map as MapIcon, Menu, Search, Satellite, Shield, X, Bell, UserRound, Factory, BrainCircuit, Clock3, ExternalLink } from 'lucide-react'
import { CircleMarker, MapContainer, Popup, TileLayer, useMap } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'
import { api } from './services/api'
import type { AlertRecord, DashboardPayload, EventRecord } from './types'
import { ClassificationBadge, RiskBadge } from './components/ui'
import { classificationDistribution, kpis as demoKpis, recentEvents as demoEvents } from './data/mockData'

const navItems = [
  ['Overview', '/', MapIcon], ['Thermal Events', '/events', Flame], ['Persistent Sources', '/persistent', Clock3], ['Industrial Areas', '/industrial', Factory], ['Satellite Imagery', '/satellite', Satellite], ['Risk Analysis', '/risk', Gauge], ['Alerts', '/alerts', Bell], ['Reports', '/reports', FileText],
] as const

const fallback: DashboardPayload = {
  source: 'Demo data fallback', rowCount: demoEvents.length,
  kpis: demoKpis.map((item) => ({ ...item, tone: item.tone })),
  timeline: { labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], values: [18, 25, 22, 33, 29, 41] },
  classificationDistribution: classificationDistribution.map((item) => ({ ...item, value: Math.round(item.value * 8) })),
  riskDistribution: [{ label: 'Critical', value: 1, count: '1', color: '#b42318' }, { label: 'High', value: 2, count: '2', color: '#e66b22' }, { label: 'Medium', value: 1, count: '1', color: '#d89224' }, { label: 'Low', value: 1, count: '1', color: '#2b7a78' }],
  events: demoEvents.map((event, index) => ({ ...event, id: `DEMO-${index + 1}`, latitude: 13 + index * 2, longitude: 76 + index, modelConfidence: 90, detectedAt: '2024-09-18T14:32:00', satelliteDate: '2024-09-15', nearestFacility: 'Demo facility', distanceKm: 0.8, probabilities: { 'Industrial Fire': 94, 'Gas Flare': 3, Wildfire: 1, Mining: 1, Other: 1 }, riskFactors: { 'FRP intensity': 80, Persistence: 78, 'Industrial proximity': 82, 'Environmental risk': 58 } })),
  mapPoints: [],
}

function MarkerLayer({ points, selectedId, onSelect, visible }: { points: DashboardPayload['mapPoints']; selectedId?: string; onSelect: (id: string) => void; visible: boolean }) {
  if (!visible) return null
  return <>{points.map((point) => <CircleMarker key={point.id} center={[point.latitude, point.longitude]} radius={point.id === selectedId ? 13 : point.risk === 'CRITICAL' ? 10 : point.risk === 'HIGH' ? 7 : 5} pathOptions={{ color: point.id === selectedId ? '#123e72' : point.risk === 'CRITICAL' ? '#b42318' : point.risk === 'HIGH' ? '#e66b22' : '#ef8b2c', fillColor: point.id === selectedId ? '#0b6eaa' : point.risk === 'CRITICAL' ? '#d43d2f' : '#f79b34', fillOpacity: .82, weight: point.id === selectedId ? 4 : 2 }} eventHandlers={{ click: () => onSelect(point.id), mouseover: (event) => event.target.openPopup(), mouseout: (event) => event.target.closePopup() }}><Popup><strong>{point.id}</strong><br />{point.classification}<br />Risk: {point.risk}</Popup></CircleMarker>)}</>
}

function MapFocus({ event }: { event?: EventRecord }) { const map = useMap(); useEffect(() => { if (event?.latitude && event.longitude) map.flyTo([event.latitude, event.longitude], 7, { duration: .7 }) }, [event, map]); return null }

function ThermalMap({ data, selected, setSelected }: { data: DashboardPayload; selected?: EventRecord; setSelected: (event: EventRecord) => void }) {
  const [layers, setLayers] = useState({ thermal: true, industrial: true, satellite: false, persistent: true })
  const pointMap = useMemo(() => data.mapPoints.filter((point) => point.classification !== 'Industrial Fire' || layers.industrial), [data.mapPoints, layers.industrial])
  const select = (id: string) => { const event = data.events.find((item) => item.id === id); if (event) setSelected(event); else api.getEvent(id).then(setSelected).catch(() => undefined) }
  return <div className="geo-map-wrap"><MapContainer center={[22.5, 79]} zoom={5} scrollWheelZoom className="geo-map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{layers.satellite && <TileLayer attribution="Esri" url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" opacity={.45} />}{layers.persistent && <MarkerLayer points={pointMap.filter((point) => (point.activeDays ?? 0) > 30)} selectedId={selected?.id} onSelect={select} visible />}{layers.thermal && <MarkerLayer points={pointMap.filter((point) => (point.activeDays ?? 0) <= 30 && point.classification !== 'Industrial Fire')} selectedId={selected?.id} onSelect={select} visible />}{layers.industrial && <MarkerLayer points={pointMap.filter((point) => point.classification === 'Industrial Fire')} selectedId={selected?.id} onSelect={select} visible />}{selected && <MapFocus event={selected} />}</MapContainer><div className="map-overlay map-title"><span className="live-map-dot" /> INDIA GIS MAP <small>VERIFIED MODEL OUTPUT</small></div><div className="map-overlay layer-box"><strong><Layers size={14} /> LAYERS</strong>{Object.entries(layers).map(([key, value]) => <label key={key}><input type="checkbox" checked={value} onChange={() => setLayers((current) => ({ ...current, [key]: !value }))} />{key === 'thermal' ? 'Thermal detections' : key === 'industrial' ? 'Industrial signals' : key === 'satellite' ? 'Satellite imagery' : 'Persistent sources'}</label>)}</div><div className="map-legend"><span><i className="legend-thermal" /> Thermal</span><span><i className="legend-industrial" /> Industrial</span><span><i className="legend-persistent" /> Persistent</span></div></div>
}

function EventPanel({ event, onClose, onShap }: { event?: EventRecord; onClose: () => void; onShap: () => void }) {
  if (!event) return <aside className="event-panel empty-event"><div className="event-panel-icon"><MapIcon size={22} /></div><h3>Select an event</h3><p>Click a marker or event row to inspect its model-scored intelligence.</p></aside>
  const factors = Object.entries(event.riskFactors ?? {})
  const probabilities = Object.entries(event.probabilities ?? {})
  return <aside className="event-panel"><div className="panel-heading"><div><span className="panel-eyebrow">Selected event</span><h2>{event.id}</h2></div><button className="plain-icon" onClick={onClose} title="Close event details"><X size={17} /></button></div><ClassificationBadge value={event.classification} /><div className="event-score"><div><span>Confidence</span><strong>{event.modelConfidence?.toFixed(1) ?? '-'}%</strong></div><div><span>Risk score</span><strong className={`score-${event.risk.toLowerCase()}`}>{event.risk} · {event.score.toFixed(1)}</strong></div></div><div className="detail-grid"><div><span>Detected</span><strong>{event.detectedAt?.replace('T', ' ') || 'Dataset record'}</strong></div><div><span>FRP</span><strong>{event.frp.toFixed(2)} MW</strong></div><div><span>Persistence</span><strong>{event.persistence}</strong></div><div><span>Nearest facility</span><strong>{event.nearestFacility || 'Not identified'}</strong></div><div><span>Distance</span><strong>{event.distanceKm?.toFixed(2) ?? '-'} km</strong></div><div><span>Satellite observation</span><strong>{event.satelliteDate || 'Dataset record'}</strong></div></div><section className="factor-section"><h3>Risk factors</h3>{factors.map(([label, value]) => <div className="factor" key={label}><div><span>{label}</span><b>{value.toFixed(0)}%</b></div><i><em style={{ width: `${Math.min(value, 100)}%` }} /></i></div>)}</section><section className="factor-section"><h3>Classification probabilities</h3>{probabilities.map(([label, value]) => <div className="probability" key={label}><span>{label}</span><i><em style={{ width: `${value}%` }} /></i><b>{value.toFixed(1)}%</b></div>)}</section><button className="primary-button shap-button" onClick={onShap}><BrainCircuit size={15} /> View SHAP analysis <ExternalLink size={13} /></button></aside>
}

function Header({ onMenu, onSearch, onNotifications, onUser }: { onMenu: () => void; onSearch: (value: string) => void; onNotifications: () => void; onUser: () => void }) { const [countryOpen, setCountryOpen] = useState(false); return <header className="light-header"><button className="mobile-menu" onClick={onMenu} title="Open menu"><Menu size={20} /></button><Link to="/" className="header-brand"><span className="header-logo"><Shield size={18} /></span><span><b>THERMO<span>GUARD</span></b><small>AI-POWERED INTELLIGENCE</small></span></Link><div className="country-select"><button onClick={() => setCountryOpen(!countryOpen)}>🇮🇳 India <ChevronDown size={14} /></button>{countryOpen && <div className="header-dropdown"><button onClick={() => setCountryOpen(false)}>🇮🇳 India</button></div>}</div><label className="global-search"><Search size={17} /><input onChange={(event) => onSearch(event.target.value)} placeholder="Search locations, facilities, or event ID..." /></label><div className="header-right"><span className="last-updated"><Clock3 size={14} /> Last updated <b>16 Sep 2026, 21:45</b></span><button className="header-action" title="Notifications" onClick={onNotifications}><Bell size={18} /><i /></button><button className="user-button" onClick={onUser}><span className="user-avatar">SK</span><span><b>S. Kumar</b><small>Operator</small></span><ChevronDown size={14} /></button></div></header> }

function Sidebar({ open, onClose }: { open: boolean; onClose: () => void }) { return <aside className={`light-sidebar ${open ? 'open' : ''}`}><div className="sidebar-brand"><span className="header-logo"><Shield size={18} /></span><b>THERMO<span>GUARD</span></b><button onClick={onClose} className="plain-icon mobile-close-light"><X size={18} /></button></div><span className="sidebar-section">WORKSPACE</span><nav>{navItems.map(([label, to, Icon]) => <NavLink key={to} to={to} end={to === '/'} onClick={onClose} className={({ isActive }) => isActive ? 'light-nav active' : 'light-nav'}><Icon size={17} /><span>{label}</span>{label === 'Alerts' && <b>08</b>}</NavLink>)}</nav><div className="sidebar-foot"><span className="sidebar-section">DATA STATUS</span><p><i /> Fusion outputs connected</p><p><i /> 173 verified test records</p><small>Backend source · FastAPI</small></div></aside> }

export function LightLayout() { const [menuOpen, setMenuOpen] = useState(false); const [notifications, setNotifications] = useState(false); const [userOpen, setUserOpen] = useState(false); const navigate = useNavigate(); return <div className="light-app"><Sidebar open={menuOpen} onClose={() => setMenuOpen(false)} /><div className="light-main"><Header onMenu={() => setMenuOpen(true)} onSearch={(value) => { if (value) navigate(`/events?search=${encodeURIComponent(value)}`) }} onNotifications={() => setNotifications(!notifications)} onUser={() => setUserOpen(!userOpen)} />{notifications && <div className="floating-menu notifications"><b>Notifications</b><p><CircleAlert size={14} /> 8 critical-risk records require review</p><p><Bell size={14} /> Backend data source connected</p></div>}{userOpen && <div className="floating-menu user-pop"><UserRound size={16} /><b>S. Kumar</b><span>Operator account</span></div>}<main className="light-content"><Outlet /></main></div>{menuOpen && <button className="light-scrim" onClick={() => setMenuOpen(false)} aria-label="Close menu" />}</div> }

export function OverviewModern() { const [data, setData] = useState<DashboardPayload | null>(null); const [selected, setSelected] = useState<EventRecord>(); const [demo, setDemo] = useState(false); const [modal, setModal] = useState(false); useEffect(() => { api.getOverview().then((value) => { setData(value); setSelected(value.events[0]) }).catch(() => { setData(fallback); setSelected(fallback.events[0]); setDemo(true) }) }, []); const model = data ?? fallback; return <div className="overview-modern"><div className="page-intro"><div><span className="section-kicker">NATIONAL THERMAL MONITORING</span><h1>Thermal Intelligence Overview</h1><p>AI-powered monitoring of thermal anomalies, industrial activity and persistent heat sources.</p></div>{demo && <span className="demo-tag">DEMO DATA · BACKEND UNAVAILABLE</span>}</div><div className="overview-grid"><ThermalMap data={model} selected={selected} setSelected={setSelected} /><EventPanel event={selected} onClose={() => setSelected(undefined)} onShap={() => setModal(true)} /></div><BottomIntelligence data={model} selected={selected} setSelected={setSelected} onShap={() => setModal(true)} /><ShapModal event={modal ? selected : undefined} onClose={() => setModal(false)} /></div> }

function BottomIntelligence({ data, selected, setSelected, onShap }: { data: DashboardPayload; selected?: EventRecord; setSelected: (event: EventRecord) => void; onShap: () => void }) { const [period, setPeriod] = useState('30D'); const alerts = data.events.slice(0, 4); const values = period === '7D' ? [12, 22, 17, 29, 24, 34, 31] : period === '90D' ? [19, 28, 24, 36, 31, 42, 39, 52, 46, 61, 55, 69] : data.timeline.values; return <div className="bottom-intelligence"><section className="intelligence-card chart-panel"><div className="card-top"><div><span className="section-kicker">ACTIVITY PULSE</span><h2>Thermal activity</h2></div><div className="periods">{['7D', '30D', '90D'].map((item) => <button className={period === item ? 'selected' : ''} key={item} onClick={() => setPeriod(item)}>{item}</button>)}</div></div><div className="mini-chart">{values.map((value, index) => <div className="chart-column" key={`${value}-${index}`} title={`${value} detections`}><i style={{ height: `${Math.max(12, value / Math.max(...values) * 100)}%` }} /><span>{index % 2 === 0 ? (data.timeline.labels[index] || 'day') : ''}</span></div>)}</div><div className="chart-footer"><span><i className="dot-blue" /> Detections</span><span><i className="dot-orange" /> FRP intensity</span></div></section><section className="intelligence-card satellite-card"><div className="card-top"><div><span className="section-kicker">SATELLITE CONTEXT</span><h2>Sentinel-2 observation</h2></div><button className="plain-icon" title="Expand satellite context"><ExternalLink size={16} /></button></div><div className="satellite-preview"><Satellite size={30} /><b>{selected?.satelliteDate || 'Dataset observation'}</b><span>Imagery integration surface ready</span><small>Selected hotspot: {selected?.id || 'none'}</small></div></section><section className="intelligence-card explanation-card"><div className="card-top"><div><span className="section-kicker">MODEL INTERPRETATION</span><h2>AI explanation</h2></div><BrainCircuit size={18} className="card-icon" /></div><p>Why this event was classified as <b>{selected?.classification || 'thermal activity'}</b></p><ul><li>Model confidence: {selected?.modelConfidence?.toFixed(1) ?? '-'}%</li><li>{selected?.explanation || 'Persistent and spatial context are available from the fused risk output.'}</li><li>Risk score: {selected?.score.toFixed(1) ?? '-'}</li></ul><button className="text-link" onClick={onShap}>View SHAP analysis <ExternalLink size={13} /></button></section><section className="intelligence-card alerts-card"><div className="card-top"><div><span className="section-kicker">PRIORITY QUEUE</span><h2>Recent alerts</h2></div><Link className="text-link" to="/alerts">View all</Link></div>{alerts.map((event) => <button className="alert-row" key={event.id} onClick={() => setSelected(event)}><RiskBadge level={event.risk} /><span><b>{event.classification}</b><small>{event.location}</small></span><ChevronDown size={14} /></button>)}</section></div> }

function ShapModal({ event, onClose }: { event?: EventRecord; onClose: () => void }) { const [shap, setShap] = useState<import('./types').ShapExplanation>(); useEffect(() => { if (event) api.getShapExplanation(event.id).then(setShap).catch(() => setShap(undefined)) }, [event]); if (!event) return null; return <div className="modal-backdrop" onClick={onClose}><section className="shap-modal" onClick={(eventClick) => eventClick.stopPropagation()}><div className="panel-heading"><div><span className="panel-eyebrow">Explainable AI</span><h2>{event.id} · SHAP analysis</h2></div><button className="plain-icon" onClick={onClose}><X size={17} /></button></div><p className="modal-copy">Direct explanation from results/shap/event_explanations.csv for this model-scored event.</p><div className="shap-columns"><div><h3>Positive contributors</h3><p>{shap?.positive || 'No SHAP row is available for this event.'}</p></div><div><h3>Negative contributors</h3><p>{shap?.negative || 'No negative contributors were returned.'}</p></div></div>{shap && <small className="shap-source">Source: {shap.source}</small>}</section></div> }

export function ModernEventsPage() { const query = new URLSearchParams(window.location.search).get('search') ?? ''; const [items, setItems] = useState<EventRecord[]>([]); const [search, setSearch] = useState(query); const [risk, setRisk] = useState(''); const [selected, setSelected] = useState<EventRecord>(); useEffect(() => { const params = new URLSearchParams({ limit: '100', ...(search ? { search } : {}), ...(risk ? { risk } : {}) }); api.getEvents(`?${params}`).then((value) => setItems(value.items)).catch(() => setItems(fallback.events)) }, [search, risk]); return <div className="catalogue-page"><div className="page-intro"><div><span className="section-kicker">VERIFIED EVENT CATALOGUE</span><h1>Thermal Events</h1><p>Search and triage model-scored thermal detections from the final fused output.</p></div></div><div className="catalogue-controls"><label><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search event ID, classification, or coordinates" /></label><select value={risk} onChange={(event) => setRisk(event.target.value)}><option value="">All risk levels</option><option value="CRITICAL">Critical</option><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option></select></div><div className="catalogue-layout"><div className="intelligence-card table-card"><table><thead><tr><th>Event</th><th>Classification</th><th>Confidence</th><th>FRP</th><th>Persistence</th><th>Risk</th><th>Location</th></tr></thead><tbody>{items.map((event) => <tr className={selected?.id === event.id ? 'row-selected' : ''} key={event.id} onClick={() => setSelected(event)}><td><b className="event-code">{event.id}</b></td><td><ClassificationBadge value={event.classification} /></td><td>{event.modelConfidence?.toFixed(1) ?? '-'}%</td><td>{event.frp.toFixed(2)} MW</td><td>{event.persistence}</td><td><RiskBadge level={event.risk} score={event.score} /></td><td>{event.location}</td></tr>)}</tbody></table></div>{selected && <EventPanel event={selected} onClose={() => setSelected(undefined)} onShap={() => undefined} />}</div></div> }

export function PersistentPage() { const [data, setData] = useState<DashboardPayload>(); useEffect(() => { api.getOverview().then(setData) }, []); const rows = (data?.events ?? []).filter((event) => (event.activeDays ?? 0) > 30); return <div className="catalogue-page"><div className="page-intro"><div><span className="section-kicker">PERSISTENCE INTELLIGENCE</span><h1>Persistent Sources</h1><p>Thermal locations with sustained activity in the verified fusion output.</p></div></div><div className="source-grid">{rows.map((event) => <button className="source-card" key={event.id}><Clock3 size={18} /><b>{event.id}</b><span>{event.activeDays?.toFixed(0)} active days · {event.detectionCount?.toFixed(0)} detections</span><RiskBadge level={event.risk} /></button>)}{!rows.length && <div className="placeholder-page compact"><Clock3 size={24} /><p>Persistent source records will appear from the connected output.</p></div>}</div></div> }

export function AlertsPage() { const [alerts, setAlerts] = useState<AlertRecord[]>([]); const [filter, setFilter] = useState(''); const [selected, setSelected] = useState<EventRecord>(); useEffect(() => { api.getAlerts().then((value) => setAlerts(value.items)) }, []); const visible = alerts.filter((alert) => !filter || alert.level === filter); return <div className="catalogue-page"><div className="page-intro"><div><span className="section-kicker">PRIORITY QUEUE</span><h1>Alerts</h1><p>Model-scored records prioritized for review.</p></div><div className="alert-filter">{['', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((item) => <button className={filter === item ? 'selected' : ''} onClick={() => setFilter(item)} key={item}>{item || 'All'}</button>)}</div></div><div className="alert-list">{visible.map((alert) => <button className="alert-card" key={alert.id} onClick={() => setSelected(alert.event)}><RiskBadge level={alert.level} /><span><b>{alert.title}</b><small>{alert.location} · {alert.id}</small></span><ExternalLink size={15} /></button>)}</div>{selected && <div className="modal-backdrop" onClick={() => setSelected(undefined)}><div onClick={(event) => event.stopPropagation()}><EventPanel event={selected} onClose={() => setSelected(undefined)} onShap={() => undefined} /></div></div>}</div> }

export function RiskPage() { const [data, setData] = useState<DashboardPayload>(); useEffect(() => { api.getOverview().then(setData) }, []); return <div className="catalogue-page"><div className="page-intro"><div><span className="section-kicker">MODEL RISK INTELLIGENCE</span><h1>Risk Analysis</h1><p>Distribution and priority signals from the final ThermoGuard risk scoring output.</p></div></div><div className="risk-overview-grid">{(data?.riskDistribution ?? []).map((item) => <div className="risk-summary" key={item.label}><span>{item.label}</span><b>{item.count}</b><i><em style={{ width: `${item.value / Math.max(...(data?.riskDistribution ?? [{ value: 1 }]).map((row) => row.value)) * 100}%`, background: item.color }} /></i></div>)}</div><div className="intelligence-card report-copy"><Gauge size={22} /><h2>Risk scoring provenance</h2><p>Scores are served from <b>results/risk/thermoguard_risk_scores.csv</b> and include thermal, persistence, industrial proximity, mining, and model confidence features.</p></div></div> }

export function ReportsPage() { return <div className="catalogue-page"><div className="page-intro"><div><span className="section-kicker">DOCUMENT CENTRE</span><h1>Reports</h1><p>ThermoGuard analysis artifacts and model reporting.</p></div></div><div className="report-list">{[['ThermoGuard Analysis Report', 'Overview of fused thermal intelligence output'], ['Model Performance Report', 'XGBoost and ResNet evaluation results'], ['Risk Assessment Report', 'Risk score distribution and priority records']].map(([title, description]) => <div className="report-card" key={title}><FileText size={21} /><span><b>{title}</b><small>{description}</small></span><button className="secondary-button" disabled title="Report export is not implemented yet"><Download size={14} /> Coming soon</button></div>)}</div></div> }

export function PlaceholderPage({ title, icon: Icon, description }: { title: string; icon: typeof MapIcon; description: string }) { return <div className="placeholder-page"><div className="placeholder-icon"><Icon size={25} /></div><span className="section-kicker">THERMOGUARD WORKSPACE</span><h1>{title}</h1><p>{description}</p><span className="ready-pill">MODULE READY FOR INTEGRATION</span></div> }
